export const dummyUsers = [
  {
    firstName: 'Ifeoluwa',
    lastName: 'Oluwayelu',
    email: 'oluwayeluifeoluwa@gmail.com',
    role: 'admin',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/12.jpg',
  },
  {
    firstName: 'Cyzygy',
    lastName: 'Admin',
    email: 'admin@cyzygy.digital',
    role: 'admin',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    role: 'user',
    status: 'inactive',
    profilePhoto: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    firstName: 'Chris',
    lastName: 'Wilson',
    email: 'chris.wilson@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    firstName: 'Sarah',
    lastName: 'Taylor',
    email: 'sarah.taylor@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    firstName: 'David',
    lastName: 'Anderson',
    email: 'david.anderson@example.com',
    role: 'admin',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    firstName: 'Sophia',
    lastName: 'Thomas',
    email: 'sophia.thomas@example.com',
    role: 'user',
    status: 'inactive',
    profilePhoto: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    firstName: 'Daniel',
    lastName: 'Jackson',
    email: 'daniel.jackson@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    firstName: 'Olivia',
    lastName: 'White',
    email: 'olivia.white@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    firstName: 'James',
    lastName: 'Harris',
    email: 'james.harris@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/6.jpg',
  },
  {
    firstName: 'Isabella',
    lastName: 'Martin',
    email: 'isabella.martin@example.com',
    role: 'user',
    status: 'inactive',
    profilePhoto: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    firstName: 'Ethan',
    lastName: 'Thompson',
    email: 'ethan.thompson@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    firstName: 'Mia',
    lastName: 'Garcia',
    email: 'mia.garcia@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    firstName: 'Alexander',
    lastName: 'Martinez',
    email: 'alexander.martinez@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Robinson',
    email: 'charlotte.robinson@example.com',
    role: 'user',
    status: 'inactive',
    profilePhoto: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    firstName: 'Benjamin',
    lastName: 'Clark',
    email: 'benjamin.clark@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    firstName: 'Amelia',
    lastName: 'Rodriguez',
    email: 'amelia.rodriguez@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/women/9.jpg',
  },
  {
    firstName: 'Lucas',
    lastName: 'Lewis',
    email: 'lucas.lewis@example.com',
    role: 'user',
    status: 'active',
    profilePhoto: 'https://randomuser.me/api/portraits/men/10.jpg',
  },
  {
    firstName: 'Harper',
    lastName: 'Lee',
    email: 'harper.lee@example.com',
    role: 'user',
    status: 'inactive',
    profilePhoto: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
];
